name: Defect Processing Pipeline

on:
  workflow_dispatch:

  push:
    branches:
      - feature/two-pipeline-defect-framework

jobs:
  defects:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Print Files
        run: |
          pwd
          ls -R